import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author noyeongdan
 */
public class Login extends javax.swing.JFrame {
    private static String id;
    String pass;
    boolean loginOK = false;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sign_Up = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        Check = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Password = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Check_pw = new javax.swing.JTextField();
        Notice = new javax.swing.JTextField();
        Sign_Up1 = new javax.swing.JButton();
        lblMain = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblPW = new javax.swing.JLabel();
        tbxID = new javax.swing.JTextField();
        tbxPW = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        btnLogin1 = new javax.swing.JButton();

        Sign_Up.setModal(true);

        jLabel5.setText("회원 가입하기");

        jLabel4.setText("이름");

        jLabel1.setText("아이디");

        Check.setText("중복확인");
        Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckActionPerformed(evt);
            }
        });

        jLabel2.setText("비밀번호");

        Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PasswordKeyReleased(evt);
            }
        });

        jLabel3.setText("비밀번호 확인");

        Check_pw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Check_pwKeyReleased(evt);
            }
        });

        Notice.setText("*비밀번호를 확인해주세요");

        Sign_Up1.setText("가입하기");
        Sign_Up1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sign_Up1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Sign_UpLayout = new javax.swing.GroupLayout(Sign_Up.getContentPane());
        Sign_Up.getContentPane().setLayout(Sign_UpLayout);
        Sign_UpLayout.setHorizontalGroup(
            Sign_UpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sign_UpLayout.createSequentialGroup()
                .addGroup(Sign_UpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Sign_UpLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel5))
                    .addGroup(Sign_UpLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(Sign_UpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(35, 35, 35)
                        .addGroup(Sign_UpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ID)
                            .addGroup(Sign_UpLayout.createSequentialGroup()
                                .addGroup(Sign_UpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Check_pw, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Notice, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Check)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Sign_UpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Sign_UpLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Sign_Up1)
                .addGap(158, 158, 158))
        );
        Sign_UpLayout.setVerticalGroup(
            Sign_UpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sign_UpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(26, 26, 26)
                .addGroup(Sign_UpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(Sign_UpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Check))
                .addGap(18, 18, 18)
                .addGroup(Sign_UpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Sign_UpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Check_pw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Notice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Sign_Up1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMain.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        lblMain.setText("로그인");

        lblID.setText("ID");

        lblPW.setText("PW");

        btnLogin.setText("로그인");
        btnLogin.setToolTipText("");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnLogin1.setText("회원가입");
        btnLogin1.setToolTipText("");
        btnLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(lblMain))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblID)
                            .addComponent(lblPW))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tbxID)
                                .addComponent(tbxPW, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMain)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(tbxID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPW)
                    .addComponent(tbxPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogin1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        
        Connection conn = null;
        PreparedStatement pstmt = null;
        ResultSet rs = null;
        
    try{
        
        Class.forName("com.mysql.cj.jdbc.Driver");
	conn = DB.getConnection();
        
	String sql = "select * from Refrigerator_management.Member";
	pstmt = conn.prepareStatement(sql);
	rs = pstmt.executeQuery();/*!!!!!!*/
	
        id = tbxID.getText();
        pass = tbxPW.getText();
        
        String query = "select * from Refrigerator_management.Member where id ='" + id + "'";
        rs = pstmt.executeQuery(query);
        if(rs.next()){
            if(id.equals(rs.getString("ID")) && pass.equals(rs.getString("password"))){
                loginOK = true;
                System.out.println("로그인 성공");
                Refrigerator fr = new Refrigerator();
                fr.setVisible(true);
                dispose();
            }
        }
        if(!loginOK){
            System.out.println("로그인 실패");
            JOptionPane.showMessageDialog(null,"로그인을 실패했습니다.", "알림", JOptionPane.ERROR_MESSAGE);
        }
        
        }catch(Exception e) {
            e.printStackTrace();
        }finally{
            try {
                if(rs != null) rs.close();
		if(pstmt!= null) pstmt.close();
		if(conn != null) conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    public String getID(){
        return this.id;
    }
    private void btnLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin1ActionPerformed
        // TODO add your handling code here:
        Sign_Up.setSize(400,350);
        Sign_Up.show();
    }//GEN-LAST:event_btnLogin1ActionPerformed

    boolean exist = false;//이미 회원인 ID인지 아닌지 구별하는 변수
    boolean press = false;//아이디 중복확인을 했는지 안했는지 검사하는 변수
    boolean check = false;//비밀번호 입력란과 비밀번호 확인란이 같은지 확인하는 변수
    private void CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckActionPerformed
        
        try {
            // TODO add your handling code here:
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

        Connection conn = null;
        PreparedStatement pstmt = null;
        ResultSet rs = null;

        ArrayList<String> exist_ID = new ArrayList<String>();
        try{
            conn = DB.getConnection();
            String sql = "select * from Refrigerator_management.Member";
            pstmt = conn.prepareStatement(sql);
            rs = pstmt.executeQuery();/*!!!!!!*/
            while(rs.next()){
                exist_ID.add(rs.getString("ID"));
            }
        }catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            try {
                if(rs != null) rs.close();
                if(pstmt!= null) pstmt.close();
                if(conn != null) conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//mySQL에서 ID값들을 가져와서 ID라는 이름의 ArrayList에 넣는다.
        exist = false;
        for(int i=0; i<exist_ID.size(); i++){
            press = true;
            if(ID.getText().equals(exist_ID.get(i))){
                exist = true;
                break;
            }
        }
        if(exist){
            JOptionPane.showMessageDialog(null,"아이디가 중복됩니다.");
            press = false;
        }
        else{
            JOptionPane.showMessageDialog(null,"아이디가 중복되지 않습니다.");
        }
    }//GEN-LAST:event_CheckActionPerformed

    private void Check_pwKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Check_pwKeyReleased
        // TODO add your handling code here:
        if(Password.getText().equals(Check_pw.getText())){
            Notice.setText("비밀번호가 일치합니다.");
            check=true;
        }else{
            Notice.setText("*비밀번호가 일치하지 않습니다.");
            check=false;
        }
    }//GEN-LAST:event_Check_pwKeyReleased

    private void Sign_Up1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sign_Up1ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

        Connection conn = null;
        PreparedStatement pstmt = null;
        ResultSet rs = null;

        try{
            conn = DB.getConnection();
            String sql = "INSERT INTO Refrigerator_management.Member VALUES(?,?,?)";
            if(!press){
                JOptionPane.showMessageDialog(null,"아이디 중복확인을 먼저 해주세요!");
            }else if(!exist && check){
                pstmt = conn.prepareStatement(sql);
                pstmt.setString(1, ID.getText());
                pstmt.setString(2, Password.getText());
                pstmt.setString(3, Name.getText());
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(null,"회원가입 되셨습니다!");
                press = false;
            }else if(!check){
                JOptionPane.showMessageDialog(null,"비밀번호가 일치하지 않습니다.");
                press = false;
            }
        }catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            try {
                if(rs != null) rs.close();
                if(pstmt!= null) pstmt.close();
                if(conn != null) conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//mySQL에 새로운 회원정보를 insert한다.

    }//GEN-LAST:event_Sign_Up1ActionPerformed

    private void PasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordKeyReleased
        // TODO add your handling code here:
        if(Password.getText().equals(Check_pw.getText())){
            Notice.setText("비밀번호가 일치합니다.");
            check=true;
        }else{
            Notice.setText("*비밀번호가 일치하지 않습니다.");
            check=false;
        }
    }//GEN-LAST:event_PasswordKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Check;
    private javax.swing.JTextField Check_pw;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Notice;
    private javax.swing.JTextField Password;
    private javax.swing.JDialog Sign_Up;
    private javax.swing.JButton Sign_Up1;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogin1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMain;
    private javax.swing.JLabel lblPW;
    private javax.swing.JTextField tbxID;
    private javax.swing.JTextField tbxPW;
    // End of variables declaration//GEN-END:variables
}
